/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    copy: typeof import('./src/components/Feature1 copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Feature1: typeof import('./src/components/Feature1.vue')['default']
    Feature2: typeof import('./src/components/Feature2.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
